<a href="https://colab.research.google.com/github/min-hee-Lee/python_workdemo/blob/master/p200_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy
- NumpPy는 Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 필수 패키지중 하나이다.
- 과학 계산을 위한 대부분의 패키지는 NumPy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용한다.
- 효율적인 다차원 배열인 ndarray(n dimensional array)는 빠른 배열 계산과 유연한 브로드캐스팅 기능을 제공한다.
- 반복문을 작성할 필요 없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수이다.
- 배열 데이터를 디스크에 쓰거나 읽을 수 있는 도구와 메모리에 적재된 파일을 다루는 도구이다.
- 선형대수, 난수 생성기등에 사용된다.
- C, C++, 포트란으로 작성한 코드를 연결할 수 있는 C API가 제공된다.

공식문서 https://numpy.org/doc/stable/

numpy 100 문제 https://github.com/rougier/numpy-100

###1. 데이터 생성

In [4]:
#!pip install numpy
import numpy as np

In [5]:
a = np.zeros(3)  #3개의 0값을 갖는 배열 생성
                  #1차원 배열 - 벡터

In [6]:
a

array([0., 0., 0.])

In [7]:
# 처음 객체들은 type(), dir()을 해본다.
print(type(a))
print(dir(a))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [8]:
# 1차원 배열 = 벡터
a = np.array([1,2,3])   #리스트로 배열 생성
a

array([1, 2, 3])

In [9]:
print(type(a))
print(dir(a))
print(len(dir(a)))

<class 'numpy.ndarray'>
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__r

In [10]:
#2차원 배열 = 행렬
b = np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [11]:
#3차원 배열 이상 = 텐서(tensor)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [12]:
# 문자 데이터가 하나라도 있으면 전체가 문자로 바뀐다.
# numpy는 homogeneous이다.
a = np.array([1,'2',3])
print(a)
print(type(a))
print(type(a[0]))

['1' '2' '3']
<class 'numpy.ndarray'>
<class 'numpy.str_'>


In [13]:
b = np.array(['a',1,True])  #전체 문자열 취급
print(b)
print(type(b))
b

['a' '1' 'True']
<class 'numpy.ndarray'>


array(['a', '1', 'True'], dtype='<U21')

In [14]:
c = np.array([1, True, 2, False])  #숫자와 논리값이 같이 나오면 숫자로 취급
print(c)
print(type(c))
c
print(type(c[0]))

[1 1 2 0]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


### np.zeros
- tuple로 인자를 넣으면 그대로 모양을 만든다.
- (2,3) : 2행 3열 행렬을 만든다.
- zeros는 기본값으로 0.(실수값)으로 값을 모두 채운다.  
a = np.zeros([2,3])  -> 일반적으로 이렇게 사용  
a = np.zeros((2,3))

In [15]:
a = np.zeros([2,3])  #실수값 0으로 배열 생성
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
a = np.zeros([2,3,4])  #[depth, 행, 렬]
a

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

### np.eye
- eye는 단위 행렬
- 숫자만 사용할 수 있다.


In [17]:
# 인자값이 1개이면 행과 열이 같다.
# 3행 3열 행렬을 생성한다.
a = np.eye(3)  #1과 0으로 채워짐
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#eye는 행과 열의 크기를 지정할 수 있다.
# 3행 2열 행렬생성
a = np.eye(3,2)
a

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [19]:
# k=1 : 크기(1)이 시작되는 위치를 지정할 수 있다 (1인덱스부터 시작)
c = np.eye(3,4, k=1) 
c

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### np.identity
- 수학에서 단위행렬은 영어로 identity matrix이다.
- 크기 한 개만 지정해서 생성할 수 있다.

In [20]:
a = np.identity(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# TypeError
# 인자 하나만 지정할 수 있다.
#a = np.identity(3,2) 
# a

### np.full
- 지정한 크기의 배열을 생성하고 채울 값을 지정할 수 있다.
- 2행 2열의 배열 생성 후 1로 채워준다.  
  np.full((2,2),1)

In [22]:
a = np.full((2,2),1)
a

array([[1, 1],
       [1, 1]])

In [23]:
b = np.full(3,4)  #1행 3열을 4로 채운다
b

array([4, 4, 4])

In [24]:
c = np.full((2,2),[1,2]) #2행 2열에 배열이 반복돼 들어간다
c

array([[1, 2],
       [1, 2]])

In [25]:
d = np.full((2,2),[[1,2],[3,4]]) #2행 2열에 각각의 배열을 넣어준다
d

array([[1, 2],
       [3, 4]])

### np.empty
- 배열을 생성하고 초기화를 지정하지 않는다.
- 메모리에 있는 값이나 이전에 사용했던 값들로 채워진다.

In [26]:
a = np.empty(3)
a

array([1., 1., 1.])

In [27]:
k = np.zeros((2,3))
k

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# zeros해서 생성한 배열이 있으면 배열의 값을 0으로 채워준다
b = np.empty((2,3))  #위에서 (이전에)사용했던 값으로 채워짐
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
c = np.empty((2,5))
c

array([[1.94159894e-316, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.61964966e-051, 5.92937314e-038, 5.49818086e-090,
        1.09689289e-071, 1.61721077e-312]])

### np.ones
- 배열의 모든 값을 1로 채운다

In [30]:
# 1행 3열의 배열 생성 후 모든 값을 1로 채운다.
a = np.ones(3)
a

array([1., 1., 1.])

In [31]:
# b = np.ones([2,3]) 리스트 형태도 가능
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

### _like
- _like가 붙으면 shape가 같게 만들어진다.
- 연산하기 위해서 shape를 맞춰야 하는 경우가 있다.

In [32]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
a.shape #배열의 구조 확인(2행 3열)

(2, 3)

In [34]:
b = np.empty_like(a)
b

array([[4607182418800017408, 4607182418800017408, 4607182418800017408],
       [4607182418800017408, 4607182418800017408, 4607182418800017408]])

In [35]:
c = np.eye(2)
c

array([[1., 0.],
       [0., 1.]])

In [36]:
c.shape

(2, 2)

In [37]:
d = np.eye(3)
d

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
d.shape

(3, 3)

In [39]:
# ValueError 
#c + d   #2행2열과 3행 3열은 합칠 수 없음

### linspace
- 동등한 간격으로 값을 생성한다.
  - 0부터 49까지 50개가 생성된다면 세 번째 num인자 값이 생략되어 있으므로 start와 end를 계산해서 default 50이 생성된다.
  - linspace(start, end, num)
  - linspace(0,49) #num=50

In [40]:
a = np.linspace(0, 49)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [41]:
b = np.linspace(0,20)
b

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [42]:
len(b)

50

In [43]:
# 1부터 10까지 3개의 요소를 생성한다.
# 기본은 endpoint=True 로 설정되어 있기 때문에 10이 포함된다.
np.linspace(1,10,3)

array([ 1. ,  5.5, 10. ])

In [44]:
# 1부터 10미만 사이에서 3개의 요소를 생성한다.
# endpoint=False로 설정되어 있으므로 10이 포함 안된다.
np.linspace(1,10,3, endpoint=False)

array([1., 4., 7.])

### logspace
- linspace 와 비슷하다.
- log scale을 사용하는 차이가 있다.
- 1부터 50까지 사이의 10개의 요소를 생성한다.
- np.logspace(1,50,10)

In [45]:
a = np.logspace(1,50,10)
a

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

### dtype
- numpy는 c언어를 기반으로 해서 만들었기 때문에 c의 데이터 타입을 차용할 수 있다.

In [46]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [47]:
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int64


In [48]:
b = np.array([1,2,3],dtype=np.int8)  #numpy데이터타입으로 지정할 수 있다.(np.int8)8은 비트
b

array([1, 2, 3], dtype=int8)

In [49]:
#np.int8은 -128 ~ 127 사이의 값을 지정할 수 있다.
c = np.array([-127, -128,17, 2, 3, -127, -128, 127], dtype=np.int8)
c

array([-127, -128,   17,    2,    3, -127, -128,  127], dtype=int8)

In [50]:
# int는 python의 int를 사용한다.
d = np.array([127, 2, 3, -127, -128], dtype=int)   #int내부는 64비트로 처리된다
d

array([ 127,    2,    3, -127, -128])

In [51]:
type(d[0])

numpy.int64

### python 도움말

In [52]:
?sum

In [53]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



### numpy 도움말

In [54]:
np.lookfor('sum')

Search results for 'sum'
------------------------
numpy.sum
    Sum of array elements over a given axis.
numpy.cumsum
    Return the cumulative sum of the elements along a given axis.
numpy.einsum
    einsum(subscripts, *operands, out=None, dtype=None, order='K',
numpy.nansum
    Return the sum of array elements over a given axis treating Not a
numpy.nancumsum
    Return the cumulative sum of array elements over a given axis treating Not a
numpy.einsum_path
    Evaluates the lowest cost contraction order for an einsum expression by
numpy.trace
    Return the sum along diagonals of the array.
numpy.ma.sum
    Return the sum of the array elements over the given axis.
numpy.Bytes0.sum
    Scalar method identical to the corresponding array attribute.
numpy.polyadd
    Find the sum of two polynomials.
numpy.ma.cumsum
    Return the cumulative sum of the array elements over the given axis.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.Bytes0.cumsum
    Scal

In [55]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
a.shape   #2행3열

(2, 3)

In [57]:
# array가 몇 차원인지 알려준다(2행=2차원)
# shape로도 알 수 있다
a.ndim 

2

In [58]:
# 데이터 타입을 알려준다.
a.dtype

dtype('int64')

In [59]:
# 요소 전체의 개수를 알려준다
# shape로도 알 수 있다 (2행 x 3열 = 6개)
a.size

6

In [60]:
# 요소당 byte수를 알려준다.
a.itemsize

8

### numpy와 python의 속도 차이(정도만 알기)

In [61]:
np.arange(10)    #range와 같은 역할

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
# numpy를 이용한 계산
%time np.sum(np.arange(1000000000))

CPU times: user 1.27 s, sys: 934 ms, total: 2.21 s
Wall time: 2.22 s


499999999500000000

In [63]:
# python을 이용한 계산
%time sum(range(1000000000))

CPU times: user 15.9 s, sys: 41.3 ms, total: 15.9 s
Wall time: 16.3 s


499999999500000000

같은 np.sum()을 사용하더라도 값을 생성하는 방법에 따라 속도가 달라진다.

In [64]:
# 오래걸림(포기)
# %time np.sum(range(1000000000))

### copy
※ 대입문 6가지    
  a = 1  
  a = b = 1  
  a, b = 1, 2  
  a, *b = 1, 2, 3  
  a += 1  
  global, nonlocal


### python copy

In [65]:
a = [1,2,3] #sequence, mutable, heterogeneous

In [66]:
b = a

In [67]:
b

[1, 2, 3]

In [68]:
a is b    #메모리 주소 비교

True

In [69]:
# a와 b가 메모리 주소를 공유
# b값을 변경하면 a도 같이 변경 된다.
b[0] = 7

In [70]:
b

[7, 2, 3]

In [71]:
a

[7, 2, 3]

list copy()

In [72]:
a = [1,2,3]

In [73]:
# copy()는 똑같은 값만 가지고 메모리는 공유하지 않는다.
b = a.copy()

In [74]:
a is b   #메모리 주소 비교

False

In [75]:
id(a)  #주소값 확인


140554412330752

In [76]:
id(b)

140554248527552

In [77]:
b[0] =8

In [78]:
b

[8, 2, 3]

In [79]:
a

[1, 2, 3]

In [80]:
print(a is b)
print(a == b)

False
False


list가 2차원일 때 

In [81]:
a = [[1,2,3]]

In [82]:
type(a)

list

In [83]:
# shallow copy
b = a.copy()

In [84]:
print(a is b)
print(a ==b)

False
True


In [85]:
print(a[0] is b[0])
print(a[0] == b[0])

True
True


list deepcopy()

In [86]:
import copy

In [87]:
a = [[1,2,3]]
b = copy.deepcopy(a)

In [88]:
print(a)
print(b)

[[1, 2, 3]]
[[1, 2, 3]]


In [89]:
print(a is b)
print(a == b)
print(a[0] is b[0]) # deep copy가 됨
print(a[0] == b[0])

False
True
False
True


[:]는 전체라는 뜻이다.
- 슬라이싱 방식으로 1차 리스트일 때는 재할당하면 deepcopy가 된다.
- 슬라이싱 2차 리스트 이상인 경우 shallow copy가 발생한다.

In [90]:
#1차원 배열일 때
a = [1,2,3]
b = a[:]
print(a is b) #주소값
print (a ==b) #요소값
b[0] = 7
print(a is b)
print (a==b)

False
True
False
False


In [91]:
#2차원 배열일 때
a = [[1,2,3]]
# 슬라이싱 2차 이상인 경우 shallow copy가 된다.
b = a[:]
print(a is b)
print (a ==b)
b[0][0] = 7
print(a is b)
print (a==b)  #a값도 b와 같이 바뀜

False
True
False
True


※python의 copy는 기본적으로 2차원부터 shallow copy를 한다.

### numpy의 copy

In [92]:
import numpy as np
a = b = np.array([1,2,3])

In [93]:
print(a is b)
print(a==b)

True
[ True  True  True]


array는 sequence타입으로 인덱싱과 슬라이싱이 가능하다.

In [94]:
a[0]  #indexing

1

In [95]:
a[:]  #slicing

array([1, 2, 3])

In [96]:
# array는 mutable이다.
# 예외가 몇 가지 있지만 mutable에 가깝다.
a[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


array는 homogeneous, sequence, mutable이다.

array deepcopy

In [97]:
a = np.array([[1,2,3]])
# numpy는 기본적으로 deepcopy이다.
b = a.copy()

In [98]:
print(a is b)

False


### as 계열
다른 데이터 타입을 가져와서 바꿔서 사용할 때는 as라는 이름이 보통 붙는다.

In [99]:
# python의 list 데이터 타입을 int ndarry로 변환
a = [1,2,3]  #python의 list
print(type(a))
print(type(a[0]))

b = np.array(a)   #numpy의 array
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [100]:
# python의 list 데이터 타입을 int ndarry로 변환(asarray())
a = [1,2,3]  #python의 list
print(type(a))
print(type(a[0]))

b = np.asarray(a)   #numpy의 array
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [101]:
# python의 list 데이터 타입을 int ndarry로 변환(asarray())
a = [1,2,3]  #python의 list
print(type(a))
print(type(a[0]))

b = np.asfarray(a)   #numpy의 array (asfarrayy하면 float으로 바꿈)
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'int'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [102]:
# python의 list 데이터 타입을 int ndarry로 변환(asarray())
a = [1.,2.,3.]  #python의 list  (1. 숫자뒤에 .점붙이면 실수타입)
print(type(a))
print(type(a[0]))

b = np.asarray(a)   #numpy의 array (위의 python타입을 그대로 가져옴)
print(type(b))
print(type(b[0]))

<class 'list'>
<class 'float'>
<class 'numpy.ndarray'>
<class 'numpy.float64'>


### 배열의 값 가져오기

#### (1) comma로 값 가져오기

In [103]:
a = [[1,2,3], [4,5,6]]  #python
b = np.array([[1,2,3], [4,5,6]]) #array

In [104]:
a[0]

[1, 2, 3]

In [105]:
# a[0,1]  # 이렇게는 못가져온다

In [106]:
a[0][1]   #인덱스를 이용해 값을 가져올 때는 행,렬을 입력해줘야함

2

In [107]:
a[slice(0,1)]

[[1, 2, 3]]

In [108]:
b[0]

array([1, 2, 3])

In [109]:
b[0, 1]

2

### (2) boolean indexing

In [110]:
a = [[1,2,3,4]]   # python list

In [111]:
# TypeError
# a > 3

In [112]:
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [113]:
b > 3

array([False, False, False,  True])

array를 scalar와 연산하면 elementwise로 계산한다.  
(elementwise : 원소별로 각각 계산이 된다.)

In [114]:
b[b>3]   #True인 값만 가져온다.

array([4])

numpy에서 boolean indexing 조건
- array만 가능하다.
- numpy True,False로만 가능하다.
- shape가 맞아야 한다.(개수가 맞을 때만 사용할 수 있다)

####(3) fancy indexing

In [115]:
b = np.arange(100).reshape([20,5])  #reshape(행, 열) 배열의 구조 변경
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [116]:
b[:]    #b 전체를 복사해서 가져와라 =b[:,:]와 같다
print(b[1])
print(b[1,2]) # 1행에 2번 인덱스값 가져와라
print(b[1:3])  #1행에서부터 3행 미만의 수를 가져와라
print(b[1:3, 2:4]) # 2번째 행에부터 4행 미만

print(b[[1,3,5]])  #1행 3행 5행 출력

print(b[[1,3,5], [0,2,4]]) #1,3,5행에서 0,2,4열에 해당되는 것만 출력

print(b[:,[0,2,4]])  #전체 행에서 0,2,4열에 해당되는 것만 출력

[5 6 7 8 9]
7
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 7  8]
 [12 13]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]]
[ 5 17 29]
[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]
 [15 17 19]
 [20 22 24]
 [25 27 29]
 [30 32 34]
 [35 37 39]
 [40 42 44]
 [45 47 49]
 [50 52 54]
 [55 57 59]
 [60 62 64]
 [65 67 69]
 [70 72 74]
 [75 77 79]
 [80 82 84]
 [85 87 89]
 [90 92 94]
 [95 97 99]]


In [117]:
# fancying indexing은 인덱싱 기법만 사용할 수 있다.
# ":" (콜론)은 슬라이싱 기법이므로 지원하지 않는다.
#b[[2:5]]

fancy indexing 은 (행,열의) 개수가 같게 지정되어야 한다.

In [118]:
b[[1,3,4],[0,2,1]]  #1행 0열, 3행 2열, 4행 1열 출력
                    # 정상처리됨

array([ 5, 17, 21])

In [119]:
#IndexError
#b[[1,3,5],[0,2]]

### 3차원 이상에서 차원 구분법

In [120]:
b = np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [121]:
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [122]:
b[0]   #0번째 깊이에 있는것(단락)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
b[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [124]:
b[0,1]

array([4, 5, 6, 7])

In [125]:
b[0,1,3]  # 0깊이 1인덱스행 3인덱스

7

### fancy indexing과 indexing 차이
  - indexing은 원래 차원에서 하나 감소해서 가져오고 fancy indexing은 원래 차원 그대로 가져온다.

In [126]:
b[0]  #indexing은 차원이 하나 감소해서 가져온다(3차원 -> 2차원으로)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
b[[0]]   #fancy indexing은 원래 3차원 그대로 가져온다

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [128]:
#b[0]  #인덱싱 2차원 가져옴
#b[0,:,:]  #인덱싱 2차원 가져옴
b[[0],:,:] #팬시 인덱싱 3차원 가져옴

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

### Ellipsis

In [129]:
b[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
b[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
type(...)

ellipsis

In [132]:
b[0]   #생략기법(인덱싱 기법)
b[0,:,:] #슬라이싱 기법
b[0,...] #Elipse기법

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [133]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [134]:
# 숫자 1,5,9만 가져온다.
b[0,:,1]   #0번째 깊이에서 1열만 가져오면 됨

array([1, 5, 9])

In [135]:
#숫자 1,5,9,3,7,11가져오기
b[0,:,[1,3]]

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [136]:
#숫자 4,  5,  6,  7, 16, 17, 18, 19 가져오기
# 각 깊이의 1행만 가져오기
b[:,1,:]


array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [137]:
b[:,1:2, :]   #원래 차원수 3차원 그대로 가져옴
#배열을 할 때는 차원수 고려해서 출력해야함.

array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]])

In [138]:
# 숫자 3,7,11,15,19,23가져오기
b[:,:,3]

array([[ 3,  7, 11],
       [15, 19, 23]])

In [139]:
# 숫자 3,7,11,15,19,23 원래 크기 그대로 가져오기(3차원)
b[:,:,[3]]

array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])

### 줄임표현(...)
출력해야 할 데이터 수가 매우 클 때 보이는 ...은 Elipsis와 다르다.

In [140]:
# out(출력)에 나오는 ...은 단순히 줄임표현이다.
np.arange(100000)

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [141]:
np.set_printoptions(edgeitems=6)   #줄임표 양쪽에 6개씩 출력되게 지정

In [142]:
np.arange(100000)

array([    0,     1,     2,     3,     4,     5, ..., 99994, 99995, 99996,
       99997, 99998, 99999])

### 연산
numpy 연산의 기본은 두 개의 shape가 같아야 한다.

In [143]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [144]:
a.shape

(3, 4)

In [145]:
b = np.arange(1,13).reshape(3,4)  #np.arange(1,13)시작값 1 끝값 13 지정
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [146]:
b.shape

(3, 4)

numpy는 elementwise로 vectorize 연산을 한다.  
vectorize는 데이터의 연산을 일괄적으로 처리하는 기능이다.

In [147]:
# 같은 위치의 요소끼리 더해준다.(elementwise(리스트에서는 안됨))
a+b    #a와 b의 shape이 같으므로 각각 같은자리 데이터끼리 연산돼서 출력

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [148]:
[1,2,3] + [4,5,6]   #python list

[1, 2, 3, 4, 5, 6]

numpy는 python함수도 ventorize 시키는 기능을 지원한다.

In [149]:
#list도 같은 위치 요소끼리 연산하고 싶을 경우
@np.vectorize
def plus(a,b):
  return a+b

plus([1,2,3], [4,5,6])

array([5, 7, 9])

In [150]:
a * b

array([[  0,   2,   6,  12],
       [ 20,  30,  42,  56],
       [ 72,  90, 110, 132]])

In [151]:
#[1,2,3] * [4,5,6]
#list는 안됨

In [152]:
c = np.matrix([[1,2],[3,4]])
c

matrix([[1, 2],
        [3, 4]])

In [153]:
type(c)

numpy.matrix

In [154]:
# matrix * matrix = 행렬곱
# 1*1+2*3  1*2+2*4
# 3*1+4*3  3*2+4*4
c * c

matrix([[ 7, 10],
        [15, 22]])

In [155]:
a = np.arange(12).reshape(3,4)
print(a)
print(a.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [156]:
b = np.arange(1,13).reshape(3,4)
print(b)
print(b.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


ndarry에서 행렬곱 연산자 @ 이다.  
python재단에서 numpy를 위해 만들어준 연산자이다.

In [157]:
#a @ b

ValueError: ignored

행렬곱을 하기 위해서는 shape가 맞아야 한다.  
T는 transpose(전치)의 약자이다.

In [160]:
b = b.T

In [161]:
print(a.shape, b.shape)

(3, 4) (4, 3)


In [162]:
a @ b

array([[ 20,  44,  68],
       [ 60, 148, 236],
       [100, 252, 404]])

함수방법으로 np.dot()을 사용할 수 있다.

In [163]:
np.dot(a, a.T)  #ndarry

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

In [164]:
b = np.matrix(b)
type(b)

numpy.matrix

In [167]:
np.dot(b, b.T)   #matrix나 배열이나 dot을 이용하면 행렬곱이 가능하다.

matrix([[107, 122, 137, 152],
        [122, 140, 158, 176],
        [137, 158, 179, 200],
        [152, 176, 200, 224]])

In [168]:
a.dot(a.T)  #메소드방식으로 사용 a자리에 반드시 객체가 와야한다

array([[ 14,  38,  62],
       [ 38, 126, 214],
       [ 62, 214, 366]])

### broadcasting
python은 배열과 숫자간에 연산을 할 수 있다.

In [169]:
#[1,2,3] + 1   #리스트와 숫자는 연산이 안된다.

TypeError: ignored

In [171]:
a = np.array([1,2,3])     #각각 요소에 1을 더함/행렬이 안맞는데 자동으로 맞춰주는 역할이 broadcasting
a + 1

array([2, 3, 4])

broadcasting이란 모양(shape)이 안맞는데, 특정한 조건에 맞으면 모양을 같게 만들어 연산하는 기능이다.  
위 연산에서 1을 a에 같은 모양으로 만들어 준다.

*** shape모양이 배수가 돼야 broadcasting이 발생한다.***

In [174]:
b = np.arange(6).reshape(2,3)
b   #2행 3열

array([[0, 1, 2],
       [3, 4, 5]])

In [175]:
c = np.array([3,4])
c  #1행 2열

array([3, 4])

행과 열이 각각 배수가 돼야 broadcasting이 발생될 수 있다.  
위의 b,c 처럼 행은 배수가 되지만 열이 배수가 되지 않으면 발생하지 않는다.

### axis
axis는 다차원 배열을 연산할 때 기준이 되는 축이다.

In [176]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [177]:
np.sum(a)    #배열 전체 요소를 누적해 더함

66

(0,0)(0,1)(0,2)(0,3)  -> 열 마다 누적  
(1,0)(1,1)(1,2)(1,3)  
(2,0)(2,1)(2,2)(2,3)  
  |
  행 마다 누적

In [178]:
np.sum(a, axis=0)    #a배열은 2차원이므로 axis 0=행 기준이다. (행마다 누적 sum)

array([12, 15, 18, 21])

In [179]:
np.sum(a, axis=1)   #a배열은 2차원이므로 axis 1=열 기준이다 (열마다 누적 sum)

array([ 6, 22, 38])

3차원 이상에서 축기준 계산

In [180]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [181]:
# 공간기준(공간마다)
np.sum(a, axis=0)    #0깊이와 1깊이의 각각 요소의 위치끼리 sum 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [182]:
#행 기준(행마다)
np.sum(a, axis=1)   #0깊이의 행끼리 합 / 1깊이의 행끼리 합

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [183]:
#열 기준(열마다)
np.sum(a,axis = 2)  #0깊이의 열끼리 합/1깊이의 열끼리 합

array([[ 6, 22, 38],
       [54, 70, 86]])

### array 모양 바꾸기

#### (1) reshape
reshape는 차원을 바꿔주는 기능을 한다.

In [186]:
a = np.arange(24)
b = a.reshape(3,8)   #3행 8열로 모양을 바꿔 b에 넣어쥼
a  #a의 모양은 그대로 유지됨

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [187]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [188]:
#a.reshape(2,3,5)  갖고있는 요소는 24개인데 30개를 만들 수 없음

ValueError: ignored

In [189]:
# 음수를 쓰면 알아서 shape을 맞춘다.
a.reshape(2,3,-1)    #2깊이 3행에 맞춰서 만들고 음수값을 넣으면 알아서 나머지를 채워줌

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [190]:
#어떤 음수값을 넣어도 상관없다.
a.reshape(2,3,-100)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [191]:
# 고정된 값을 줄 때 배열의 크기를 고려해서 줘야한다.
#a.reshape(3,5,-1)  #3깊이에 5행은 15개 자리가 생기는데 a에는 24개의 요소가 있으므로 개수가 안맞아 생성할 수 없음

ValueError: ignored

In [192]:
# 음수를 2개 사용할 수 없다
# 음수는 다른 차원들이 정해진 상황에서 남은 하나의 차원만 알아서 맞춰준다
# a.reshape(3,-1,-1)

ValueError: ignored

In [193]:
#음수값이 1개이면 위치는 어디에 오든 상관없다.
a.reshape(3,-1,2) #3깊이 2열을 지정하고 행은 알아서 맞춰서

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [194]:
a.reshape(-1,4,2)  # 4행 2열을 지정하고 깊이는 알아서 맞춰서

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

#### (2) reshape으로 차원 늘리기

In [196]:
# 1차원 -> 2차원으로
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [197]:
# 1차원 -> 3차원으로
a = np.arange(6).reshape(1,3,2)
a

array([[[0, 1],
        [2, 3],
        [4, 5]]])

### resize


In [198]:
# size는 원소 개수를 알려준다.
a = np.arange(24)
print(a.size)
print(len(a))

24
24


In [199]:
# mutable이다. return이 없고 자기 자신을 바꾼다. -> reshape와 차이점1
# 원래의 원소 개수와 변경하는 원소 개수가 안 맞아도 된다. (0으로 채워준다) -> reshape와 차이점 2
b = np.arange(24)
b.resize((2,3,8))
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]],

       [[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0,  0,  0]]])

### array 쪼개기

split

In [208]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [209]:
# indices_or_sections
a = np.split(a,3,axis=0)   #1차원 배열을 3개로 쪼갠다
print(a)
print(type(a))  #그러면 list에 쪼개진 배열을 넣어줌 = list로 리턴
print(a[0], type(a[0]))

[array([0, 1, 2, 3, 4, 5, 6, 7]), array([ 8,  9, 10, 11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20, 21, 22, 23])]
<class 'list'>
[0 1 2 3 4 5 6 7] <class 'numpy.ndarray'>


hsplit & vsplit

split는 axis 파라미터가 있다.  
default:axis=0

In [210]:
a = np.arange(24)
b = a.reshape(4,6)
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [211]:
np.split(b,2)  #default가 0이므로 행을 기준으로 쪼개짐

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [212]:
np.split(b,2, axis=0)  #위랑 같음 (2차원 그대로 유지)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])]

In [214]:
#수평으로 가져올 때
np.hsplit(a,2)   #행을 기준으로 2개로 쪼개겠다 (2개로 나눠진 그대로 가져옴 1차원으로 가져옴)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])]

In [213]:
np.split(b,2, axis=1)  #1을 주면 열을 기준으로 쪼개짐

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

In [216]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [218]:
np.hsplit(b,2)  #???? 설명 못함

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23]])]

indices_or_sections
- split 시리즈 함수들의 두 번째 파라미터 이름이 indices_or_sections이다.
- 숫자를 묶어서 넣으면 구간으로 쪼개진다.

In [219]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [220]:
#section
# 처음부터 ~ 2미만 : [0,1]
# 2부터 ~ 3미만 : [2]
# 3부터 ~ 끝까지 : [3,4,5...]
np.hsplit(a, (2,3))   #2미만까지/2에서 3미만까지/나머지 로 나눔

[array([0, 1]),
 array([2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
        20, 21, 22, 23])]

### array 합치기

In [221]:
a = np.arange(24)
x, y, z = np.split(a,3) # a를 3개로 쪼개서 x,y,z에 넣어라

In [222]:
print(x)
print(y)
print(z)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]


hstack & vstack

In [223]:
np.hstack((x,y))  #hstack 1차원 배열로 합침

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [224]:
np.vstack((x,y))  #hstack 열단위로 1차원 배열로 합침

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

dstack
- dstack은 합쳐서 3차원으로 만들어준다.
- 합칠 array들이 1차원, 2차원일 경우는 차원을 늘린 뒤 합친다.
- 합쳐지는 차원은 axis=2이다.

In [225]:
print(x)
print(y)  #둘 다 1차원 배열

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]


In [227]:
c = np.dstack((x,y))
c

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11],
        [ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [228]:
c.shape

(1, 8, 2)

In [229]:
x = x.reshape(2,4)
y = y.reshape(2,4)

In [230]:
print(x)
print(y)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [231]:
c = np.dstack((x,y))
c

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [232]:
c.shape

(2, 4, 2)

### concatenate
concatenate는 axis 방향에 그대로 합쳐준다.  
※ stack은 axis방향에 새로운 차원을 만들어 합쳐준다.

In [233]:
a = np.arange(12).reshape(3,4)
x,y = np.split(a,2,axis=1)

In [234]:
print(x)
print(y)

[[0 1]
 [4 5]
 [8 9]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [235]:
# 원래 shape크기 그대로 유지한다.
np.concatenate((x,y))  #axis=0 /가로방향으로 합쳐짐/2차원 그대로 유지

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [ 2,  3],
       [ 6,  7],
       [10, 11]])

In [236]:
# shape 크기를 1개 증가해서 합친다
np.stack((x,y))  #기본 axis = 0

array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[ 2,  3],
        [ 6,  7],
        [10, 11]]])

### 차원 확장

reshape

In [237]:
a = np.arange(12).reshape(3,4)  #1차원을 2차원으로
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

stack

In [240]:
# 3차원으로 확장
# tuple에 원소가 1개 있으면 차원만 확장시켜 준다.
np.stack((a,))  #2차원을 3차원으로

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

newaxis
- 인덱싱할 때 np.newaxis를 쓰면 차원을 늘릴 수 있다.

In [241]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [242]:
a.shape

(3, 4)

In [243]:
a[0]  #인덱싱을 이용해 가져오는 방법

array([0, 1, 2, 3])

In [244]:
a[np.newaxis]  #2차원을 3차원으로 가져옴

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

슬라이싱을 할 때 np.newaxis를 쓰면 차원을 늘릴 수 있다.

In [245]:
a[:,:]  #슬라이싱으로 모두 가져오기

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [246]:
a[np.newaxis,:]  #그대로 가져오면서 2차원을 3차원으로 늘림 = 1,3,4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [247]:
a[:,np.newaxis]  # 3깊이로 가져옴 = 3,1,4

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [248]:
a[:,np.newaxis].shape

(3, 1, 4)

In [249]:
a[:,:,np.newaxis]   #3,4,1

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

In [250]:
a[:,:,np.newaxis].shape

(3, 4, 1)

In [251]:
np.newaxis is None  #np.newaxis자리에 None을 써도 된다

True

np.newaxis 대신에 None을 써도 된다.  
None은 직관적이지 않고 헷갈려서 np.newaxis를 만들었다.  
numpy를 만들 때 python의 모든 연산자를 다 사용해서 남은 연산자가 없었다. 그래서 None을 이용했다.

In [252]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

expand_dims

In [253]:
np.expand_dims(a,0)  #a[np.newaxis:,:] 와 같다 / 공간1이 생김(깊이)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [254]:
np.expand_dims(a,1)  #a[:,np.newaxis,:] 와 같다 / 공간3,1행4열

array([[[ 0,  1,  2,  3]],

       [[ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11]]])

In [255]:
np.expand_dims(a,2)  #a[:,:,np.newaxis]와 같다 /공간3 4행 1열

array([[[ 0],
        [ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6],
        [ 7]],

       [[ 8],
        [ 9],
        [10],
        [11]]])

### array 한 줄로 펴기

flatten

In [256]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [257]:
# flatten()은 결과를 return하고 메모리의 값은 변경되지 않는다.(원래값은 변경하지 않는다)
b = a.flatten()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [259]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

swapaxes

In [261]:
a = np.array([[1],[2]]) #2차원 2행 1열 배열 생성
a

array([[1],
       [2]])

In [262]:
a.shape

(2, 1)

In [263]:
# a의 0번 차원과 1번 차원을 서로 교환한다.
b = np.swapaxes(a,1,0)
b

array([[1, 2]])

In [264]:
a.T

array([[1, 2]])