<a href="https://colab.research.google.com/github/min-hee-Lee/python_workdemo/blob/master/p601_%EA%B8%B0%EA%B3%84%ED%95%99%EC%8A%B5_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%A0%84%EC%B2%98%EB%A6%AC_%EB%B2%94%EC%A3%BC%ED%98%95_%EB%B3%80%EC%88%98_%EC%B2%98%EB%A6%AC(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 【범주형 변수처리】

### 변수 
기계학습에서는  column = feature = dimension = variable을 혼용해서 사용한다.  

1 범주형 변수(Categorical Data)=질적변수(Qualitative Variable) : 몇개의 범주로 나누어진 자료를 의미
 - 명목형(Nominal Data): 성별, 성공여부, 혈액형 등 순서를 매길 수 없고 셀수 있다는 특징이 있다.
 - 순서형(Ordinal Data) : 교육수준, 만족도등  그들 사이에 순서 관계가 존재하는 자료

2 수치형 변수 = 양적변수(): 이산형과 연속형으로 이루어진 자료를 의미
  - 이산형(Discrete Data) :출산횟수, 불량품 수, 사고건수, 차량대수 등 이산적인 값을 갖는 데이터로  수치적인 의미를 가지나 소수점의 형태로 표현되지 못하는 데이터를 의미
  - 연속형(Continuous Data) : 신장, 체중, 시간, 길이 등 연속적인 값을 가지고 소수점으로 표현이 가능한 데이터를 의미



더미변수란 범주형 변수에 있는 범주 각각을 컬럼으로 변경하고, 원본 컬럼의 값이 해당 범주에 속하는지 여부에 따라 1 혹은 0으로 채운 변수이다.  
pd.get_dummies(df, columns=['범주형변수'])

- 범주형 변수 변환
  - 원핫인코딩(One-hot-encoding), 더미코딩(dummy coding), 이펙트코딩(Effect coding), 숫자로 표현된 범주형 특성, 레이블인코딩(Label encoding), 특징 해싱(Feature Hashing)

- 수치형 변수 변환 (*옆의 괄호는 Scikit Learn의 함수명)
  - 선형변환: 최소최대 스케일링(MinMaxScaler), 표준화(StandardScaler), 로버스트 스케일링(RobustScaler), 균등분포/RankGauss (QuantileTransformer)
  - 비선형변환: 로그변환, 거듭제곱변환(PowerTransformer - Boxcox, YeoJohnson), 정규화(Normalizer - L1, L2, Max)
  - 기타: 구간분할 (=이산화, binning), 순위 변환

**iris 데이터의 target값인 범주형 변수를 더미변수 형태로 대체**


In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()
iris = pd.DataFrame(iris.data, columns=iris.feature_names)
iris['target'] = load_iris().target

In [ ]:
iris['target'].sample(10)

70     1
122    2
107    2
9      0
133    2
105    2
138    2
45     0
56     1
99     1
Name: target, dtype: int64

In [ ]:
iris['target'] = iris['target'].replace([0,1,2],['Setosa', 'Versicolour', 'Virginica'])
#iris['target'] = iris['target'].map({0:'Setosa', 1:'Versicolour', 2:'Virginica'})
iris['target'] 

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: target, Length: 150, dtype: object

In [ ]:
iris_dummy = pd.get_dummies(iris, columns=['target'])
iris_dummy

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target_Setosa  target_Versicolour  target_Virginica  
0                1                   0                 0  
1                1                   0                 0  
2                1                   0                 0  
3                1                   0                 0  
4                1                   0                 0  
..             ...                 ...               ...  
145              0                   0                 1  
146              0                   0                 1  
147              0                   0                 1  
148              0                   0                 1  
149              0                   0                 1  

[150 rows x 7 columns]

### label encoding
  label encoding은 문자열 데이터에 고유한 라벨 번호를 매개는 것이다.

In [ ]:
import seaborn as sns
iris = sns.load_dataset('iris')
iris.sample(5)

sepal_length  sepal_width  petal_length  petal_width    species
40            5.0          3.5           1.3          0.3     setosa
6             4.6          3.4           1.4          0.3     setosa
117           7.7          3.8           6.7          2.2  virginica
39            5.1          3.4           1.5          0.2     setosa
131           7.9          3.8           6.4          2.0  virginica

In [ ]:
# 문자열 데이터
iris.species

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [ ]:
# map으로 label encoding 할 수 있다.
iris.species.map({'setosa':0, 'versicolor':1, 'virginica': 2})

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species, Length: 150, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
ll = LabelEncoder()

In [ ]:
# 1차원으로 넣어도 된다.
# preprocessing은 fit_transform으로 한번에 할 수 있다.
ll.fit_transform(iris.species)

#ll.fit_transform(iris['species'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
#  2차원으로 넣으면 오히려 warning이 뜬다.
# sklearn이 체계적이지 않은 면이 있다.
# ravel() 또는 column_or_1d 사용하라고 뜬다.
ll.fit_transform(iris[['species']])

/usr/local/lib/python3.8/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.utils import column_or_1d

column_or_1d(iris['species'])
ll.fit_transform(column_or_1d(iris['species']))

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### one hot encoding
문자열 데이터를 column으로 바꾸고, 해당하는 위치에만 1로 한다.

In [ ]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

In [ ]:
# return sparse matrix  이다.
# 0이 많은 희소행렬은 메모리 효율성을 위해서 압축된 형식의 sparse matrix로 만든다
ohe.fit_transform(iris[['species']])

<150x3 sparse matrix of type '<class 'numpy.float64'>'
	with 150 stored elements in Compressed Sparse Row format>

In [ ]:
# toarray( )는 numpy로 바꿔줘서 값을 확인할 수 있다.
ohe.fit_transform(iris[['species']]).toarray()

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [ ]:
# 다시 문자로 바꿀 수 있다.
ohe.inverse_transform([[1,0,0],[0,1,0],[0,0,1]])

array([['setosa'],
       ['versicolor'],
       ['virginica']], dtype=object)

https://lovelydiary.tistory.com/417  
명목형 데이터에 대한 개념 계층 생성
https://hongjinhyeon.tistory.com/110